sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install --upgrade "pip<8.0" "setuptools<20.0"; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]] || [[ $TRAVIS_PYTHON_VERSION == "pypy3-2.4.0" ]]; then pip install --upgrade "pip<10.0" "setuptools<24.0"; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install "pymysql<0.7.0"
  - pip install "pycparser<2.19" coveralls
  - pip install twine
env: DB_NAME=migratore_test DB_HOST=127.0.0.1 DB_USERNAME=root DB_PASSWORD=""
before_script: mysql -e "create database migratore_test;"
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=migratore setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: fcdn+q0hfjSoquKJvhNEz93+U8q5CZsom9fg3kQJhW8DTDVFDmIyqsWf7VNgU5hIuzbc9bC+i95DWsfzbZ5x0K+Z77GADQqFpYfNy9A8cAoZ8aRdhi5AwaFWSfvrhzmT2UQruyoA/z9ipBDvkpkq7ipb832mfczlosPGiAnHqTI=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
