dist: trusty
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy3"
matrix:
  include:
  - python: 3.8
    dist: xenial
  - python: 3.9
    dist: xenial
  - python: pypy
    dist: xenial
  - python: pypy3
    dist: xenial
services:
  - mysql
before_install:
  - pip install --upgrade pip setuptools
install:
  - pip install -r requirements.py2.txt
  - pip install pymysql
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then pip install coveralls; fi
env: DB_NAME=migratore_test DB_HOST=127.0.0.1 DB_USERNAME=root DB_PASSWORD=""
before_script: mysql -e "create database migratore_test;"
script:  if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run --source=migratore setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coveralls; fi
