sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install "pymysql<0.7.0"
  - pip install coveralls
  - pip install twine
env: DB_NAME=migratore_test DB_HOST=127.0.0.1 DB_USERNAME=root DB_PASSWORD=""
before_script: mysql -e "create database migratore_test;"
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=migratore setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: FyiPfB5blg/SG04TfwRul3lnLnLExAylrczdUCJYnc3otwXRrV9NhdA7qDm1zuBDG1pW0fQY8Xrv5jhy2+sKPFHQo7E1hO9PeHMzIRVcm1KBcjxZdiY5ZVpftc8EuE293FZxRyB0tuXwiIHTNGQInEvkOBpgpfR0oa/LtcCDAu4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
