sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"
install:
  - pip install -r requirements.txt
  - pip install MySQL-Python
  - pip install coveralls
env: DB_NAME=migratore_test DB_HOST=127.0.0.1 DB_USERNAME=travis DB_PASSWORD=
before_script: mysql -e "create database migratore_test;"
script: coverage run --source=migratore setup.py test
after_success: coveralls
